### ISSUE TITLE
1.3 Casos de uso

### ISSUE THREAD

**Issue by dangarsoftpoli** [ISWPOLI/TANGRAM#4]
levantamiento de rquerimientos de los 3 proyectos

**Comment by MichaelBordaPoli** [comment]
Se adjuntan formato formato-ieee-830-SGDPH con los requerimientos
[formato-ieee-830-SGDPH.docx](https://github.com/ISWPOLI/TANGRAM/files/1965005/formato-ieee-830-SGDPH.docx)
