### ISSUE TITLE
2.2.3.4  interfaz de imagenes  Comparador imágenes diagnosticas

### ISSUE THREAD

**Issue by dangarsoftpoli** [ISWPOLI/TANGRAM#41]
construccion de crud en html5 para  interfaz   de imagenes  Comparador imágenes   diagnosticas
Crear imagenes
consultar imagenes
actualizar imagenes
Eliminar imagenes
Backup imágenes

**Comment by elbetancourt1** [comment]
Interfaz comparador de imágenes
