### ISSUE TITLE
1.3.1 History map

### ISSUE THREAD

**Issue by dangarsoftpoli** [ISWPOLI/TANGRAM#8]
Creacion de un history map para el uso general de las issues e historias  al planear la ejecucion de los 3 proyectos

**Comment by MichaelBordaPoli** [comment]
Se adjunta planeación del mapa de historias.
[listados de historias para sprints.xlsx](https://github.com/ISWPOLI/TANGRAM/files/1965024/listados.de.historias.para.sprints.xlsx)
[mapa de historias 28-04-2018.pdf](https://github.com/ISWPOLI/TANGRAM/files/1965026/mapa.de.historias.28-04-2018.pdf)
